### ISSUE TITLE
Android Class Assignment #3 almost done

### ISSUE THREAD

**Issue by tonytamsf** [tonytamsf/AndroidSimpleTwitterClient#2]
1) able to login to twitter api
2) show the hometimeline
3) didn't do compose a tweet
4) didn't do offline twitter

/cc @nesquena @timothy1ee

**Comment by nesquena** [comment]
Nice, yeah I would say try and get the compose tweet view done since I think it helps cement some of the concepts we introduced last week. Offline tweets is interesting too since it gives you a chance to play with activeandroid. As always, let us know if there's any questions you have after completing the assignment and we will be happy to answer them. This week is an important week as you can probably see since this app contains most of the key concepts you need to make android apps.
